# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/

name = "tai-sanh-landing-vibe"

# Cloudflare Pages compatibility settings
compatibility_date = "2025-10-27"

[build]
# Override the default build command to skip --frozen-lockfile
# This allows Bun to update the lockfile if peer dependencies change
command = "bun install && bun run build"

[build.environment]
NODE_VERSION = "18"

# Production environment
[env.production]
# Add any production-specific environment variables here
